workspace:
  base: /wrkspace
  path: src/github.com/karantin2020/hello-drone

clone:
  git:
    image: plugins/git
    depth: 3

pipeline:
  # these steps define a parallel execution
  # group and will fan out.

  build:
    image: alpine:edge
    commands:
      - echo this step should fail
      - exit 1
  test:
    image: alpine:edge
    commands:
      - echo this step should execute, despite failure
    when:
      status: [ failure ]
