workspace:
  base: /wrkspace
  path: src/github.com/karantin2020/hello-drone

clone:
  git:
    image: plugins/git
    depth: 3

pipeline:
  # these steps define a parallel execution
  # group and will fan out.

  build:
    image: alpine:edge
    commands:
      - echo this step should not fail
      - echo DRONE_JOB_NUMBER ${DRONE_JOB_NUMBER}
      - exit 0
  test:
    image: alpine:edge
    commands:
      - echo this step should execute when success
      - echo ${DRONE_COMMIT}
      - echo ${DRONE_BUILD_EVENT}
      - echo ${DRONE_BUILD_STARTED}
      - echo ${DRONE_JOB_NUMBER}
      - echo ${DRONE_DEPLOY_TO}
    when:
      status: [ success ]

  deploy:
    image: alpine:edge
    commands:
      - echo deploy step
      - exit 0
    when:
      event: deployment
      environment: staging
